# Generated by Django 2.2.16 on 2022-08-17 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220816_1515'),
        ('reviews', '0005_auto_20220816_2025'),
    ]

    operations = [
    ]
